"""
Database helper functions for fact-based semantic memory model.
Manages users, preferences (fact), and interaction log (episodic memory).
"""

import os
import json
from typing import Optional, Dict, Any, List
from datetime import datetime, timezone
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set in .env")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


# ============================================================================
# User Management
# ============================================================================

def get_or_create_user(email: str) -> str:
    """Get user ID by email, or create user if doesn't exist."""
    result = supabase.table("user_profile").select("user_id").eq("email", email).execute()

    if result.data:
        return result.data[0]["user_id"]

    # Create new user
    new_user = supabase.table("user_profile").insert({"email": email}).execute()
    return new_user.data[0]["user_id"]


def get_user_by_id(user_id: str) -> Optional[Dict[str, Any]]:
    """Fetch user by ID."""
    result = supabase.table("user_profile").select("*").eq("user_id", user_id).execute()
    return result.data[0] if result.data else None


# ============================================================================
# User Preferences (Fact-Based Semantic Memory)
# ============================================================================

def get_or_create_preferences(user_id: str) -> Dict[str, Any]:
    """Get or create user preferences (fact)."""
    result = supabase.table("user_preferences").select("*").eq("user_id", user_id).execute()

    if result.data:
        return result.data[0]

    # Create new preferences
    new_prefs = supabase.table("user_preferences").insert({
        "user_id": user_id,
        "fact": None
    }).execute()

    return new_prefs.data[0]


def get_user_preferences(user_id: str) -> Dict[str, Any]:
    """Fetch user preferences (fact)."""
    result = supabase.table("user_preferences").select("*").eq("user_id", user_id).execute()
    return result.data[0] if result.data else get_or_create_preferences(user_id)


def update_preference_fact(user_id: str, fact: str) -> Dict[str, Any]:
    """
    Update user's preference fact (semantic memory summary).

    Args:
        user_id: User ID
        fact: Text summary generated by Claude

    Returns:
        Updated preference record
    """
    update_data = {
        "fact": fact,
        "updated_at": datetime.now(timezone.utc).isoformat()
    }

    result = supabase.table("user_preferences").update(update_data).eq("user_id", user_id).execute()
    return result.data[0] if result.data else {}


# ============================================================================
# Interaction Log (Episodic Memory)
# ============================================================================

def log_feedback(user_id: str, liked_books: List[str], disliked_books: List[str]) -> str:
    """
    Log user feedback from a single query session.

    Args:
        user_id: User ID
        liked_books: Books user voted 👍 for
        disliked_books: Books user voted 👎 for

    Returns:
        interaction_log_id
    """
    result = supabase.table("interaction_log").insert({
        "user_id": user_id,
        "liked_books": liked_books,
        "disliked_books": disliked_books,
        "distilled": False
    }).execute()

    return result.data[0]["id"] if result.data else None


def get_recent_interactions(user_id: str, limit: int = 10) -> List[Dict[str, Any]]:
    """Get recent feedback interactions for a user."""
    result = supabase.table("interaction_log").select("*").eq(
        "user_id", user_id
    ).order("timestamp", desc=True).limit(limit).execute()

    return result.data


def get_all_feedback(user_id: str) -> Dict[str, List[str]]:
    """
    Get all liked and disliked books from interaction history.
    Used for fact generation.
    """
    interactions = get_recent_interactions(user_id, limit=100)

    all_liked = set()
    all_disliked = set()

    for interaction in interactions:
        all_liked.update(interaction.get("liked_books", []))
        all_disliked.update(interaction.get("disliked_books", []))

    return {
        "liked_books": list(all_liked),
        "disliked_books": list(all_disliked)
    }


def mark_interactions_as_distilled(user_id: str) -> int:
    """Mark interaction_log records as distilled."""
    result = supabase.table("interaction_log").update({
        "distilled": True
    }).eq("user_id", user_id).eq("distilled", False).execute()

    return len(result.data) if result.data else 0


def get_undistilled_users() -> List[str]:
    """Get list of users with undistilled interactions."""
    result = supabase.table("interaction_log").select("DISTINCT user_id").eq(
        "distilled", False
    ).execute()

    return [row["user_id"] for row in result.data] if result.data else []


# ============================================================================
# Statistics
# ============================================================================

def get_user_stats(user_id: str) -> Dict[str, Any]:
    """Get summary statistics about a user."""
    prefs = get_user_preferences(user_id)
    interactions = get_recent_interactions(user_id, limit=100)
    feedback = get_all_feedback(user_id)

    return {
        "total_interactions": len(interactions),
        "total_liked_books": len(feedback.get("liked_books", [])),
        "total_disliked_books": len(feedback.get("disliked_books", [])),
        "has_fact": prefs.get("fact") is not None,
        "fact_preview": (prefs.get("fact", "")[:100] + "...") if prefs.get("fact") else None,
        "updated_at": prefs.get("updated_at")
    }
