"""
User Profile Endpoints - Simplified

POST /feedback - Record liked/disliked books from recommendation session
GET /user-profile - Get user's semantic memory (preference fact)
"""

from typing import List
from pydantic import BaseModel
import db_helpers


class FeedbackRequest(BaseModel):
    """Record feedback from a recommendation session."""
    user_email: str
    liked_book_titles: List[str]
    rejected_book_titles: List[str]


class FeedbackResponse(BaseModel):
    """Response from /feedback endpoint."""
    success: bool
    message: str
    feedback_count: int


class UserProfileResponse(BaseModel):
    """User's semantic memory (preference fact)."""
    user_email: str
    fact: str  # The distilled preference summary
    updated_at: str
    total_interactions: int


# ============================================================================
# Feedback Endpoint
# ============================================================================

async def handle_feedback(request: FeedbackRequest) -> FeedbackResponse:
    """
    Record user feedback from a recommendation session.

    Logs liked/disliked books to interaction_log (episodic memory).
    Distillation job will later convert this to a preference fact.

    Flow:
    1. Get or create user
    2. Log feedback to interaction_log
    3. Return feedback count
    """
    user_id = db_helpers.get_or_create_user(request.user_email)

    # Log this session's feedback (episodic memory)
    db_helpers.log_feedback(
        user_id=user_id,
        liked_books=request.liked_book_titles,
        disliked_books=request.rejected_book_titles
    )

    # Get total feedback count
    interactions = db_helpers.get_recent_interactions(user_id, limit=100)
    feedback_count = len(interactions)

    return FeedbackResponse(
        success=True,
        message=f"Feedback recorded ({feedback_count} total sessions). Preferences will be updated by distillation job.",
        feedback_count=feedback_count
    )


# ============================================================================
# User Profile Endpoint
# ============================================================================

async def handle_get_user_profile(user_email: str) -> UserProfileResponse:
    """
    Get user's semantic memory (preference fact).

    Returns the distilled preference summary that was generated by the distillation job.
    """
    user_id = db_helpers.get_or_create_user(user_email)
    prefs = db_helpers.get_user_preferences(user_id)
    stats = db_helpers.get_user_stats(user_id)

    return UserProfileResponse(
        user_email=user_email,
        fact=prefs.get("fact") or "No preferences recorded yet. Submit feedback to generate profile.",
        updated_at=prefs.get("updated_at") or "",
        total_interactions=stats.get("total_interactions", 0)
    )
